### PR TITLE
update cli doc

### PR DESCRIPTION
**Pull request by YouHang**

### CODE REVIEW

**Comment by llundquist** [comment]
Hi, @YouHang Could you open this PR in our working area rather than in production? I think you might see, that file was updated more recently than this one.

**Comment by YouHang** [comment]
you mean that I reopen a pr to the repo Bluemix-Docs/vpc?

**Comment by llundquist** [comment]
Hello, @YouHang I was reviewing the CLI reference on staging today and I think these changes may already be posted there. It would be very helpful if you can review that document in comparison to this document, just to make sure all of your updates were included. Thank you! If you need to add anything, yes, please open a new PR on the staging repo. I am going to close this one because I can't merge it here.

**Comment by YouHang** [comment]
Got it, thanks!

**Pull request closed without merging**
