### PR TITLE
Update profile name

### PR DESCRIPTION
**Pull request by mlgordon**

### CODE REVIEW

**Comment by llundquist** [comment]
Please open PRs on staging unless it is a dire emergency.

**Comment by mlgordon** [comment]
Will do - thanks!

**Comment by llundquist** [comment]
Ok, I now know that this feature has gone live today, so it is a dire emergency. Merging. Next time more notice will be greatly appreciated! Thank you for the update, I know our customers will appreciate it.

**Comment by ibm-cos-help** [comment]
We also mention this in other places, in the CLI walkthrough for example. Let's find all instances.

**Comment by llundquist** [comment]
I believe we have found them in 2 other places and addressed them on staging today. Thank you.

**Pull request merged**
