### PR TITLE
Updated storage info for VPC infrastructure

### PR DESCRIPTION
**Pull request by donslovenkai**
Information updated for block storage VPC market launch

### CODE REVIEW

**Comment by llundquist** [comment]
@donslovenkai and @ibm-cos-help I am not sure why this PR is opened on production, and also I don't know how to resolve 2 of the 3 merge conflicts. I do not think we ought to delete the information that we provide a boot volume, just because now we are adding block storage, should we? It is pretty basic but good to know. One of the merge conflicts is just because I added the search keywords.

**Comment by llundquist** [comment]
I did my best.

**Comment by llundquist** [comment]
Not merging at this time, because this PR is on production. Shall I remove it and move to staging so we can test?

**Comment by ibm-cos-help** [comment]
Let's move this PR to staging @donslovenkai

**Comment by llundquist** [comment]
I will move the PR to staging today. It has the benefit that I can record it as a closed issue for doc week. :)

**Comment by llundquist** [comment]
Closing this PR, it has been moved into staging.

**Pull request closed without merging**
