### PR TITLE
Add error message to vpc doc

### PR DESCRIPTION
**Pull request by guyujie**
https://github.ibm.com/riaas/cland/issues/1503

### CODE REVIEW

**Comment by guyujie** [comment]
@llundquist Please review.

**Comment by llundquist** [comment]
yes, I would like to give this PR an editorial pass, will do.

**Comment by llundquist** [comment]
Wait, this PR looks as if it is on production. It needs to be opened on staging. Let me double check.

**Comment by llundquist** [comment]
Closing to move to staging.

**Comment by llundquist** [comment]
Please open the PR here: https://github.ibm.com/Bluemix-Docs/vpc

**Comment by guyujie** [comment]
Create PR to staging: https://github.ibm.com/Bluemix-Docs/vpc/pull/616

**Pull request closed without merging**
